### ISSUE TITLE
Отчетность по заказам

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#11]
[пример отчетности.xlsx](https://github.com/8clever/betacall/files/3144456/default.xlsx)

необходимо создать отчетность согласно примеру во вложении. отчетность должна сниматься по фильтру дате 1 день или несколько суммарно(выбирать из календаря).
необходима выгрузка в эксель. Статистику выгружать со страницы обработанных заказов.

**Comment by andreyeduardovich** [comment]
выгрузка может быть с любого места. можно с центральной страницы. https://niti.betacall4all.ru/admin/

**Comment by andreyeduardovich** [comment]
Иван, нужно сделать так, чтобы отчет был в одном документе и по всем заказам. может быть на центральной странице сделать итоговую такую выгрузку по всем заказам. это нужно именно им в одном отчете и по всем заказам. 

и к дате проставления итогового статуса нужно еще и время.

как-то так(((

**Comment by andreyeduardovich** [comment]
и колонка название ИМ нужна

**Comment by andreyeduardovich** [comment]
нет, погоди. завтра скажу итоговую версию. не на главной странице это надо. я завтра еще раз подумаю.

**Comment by andreyeduardovich** [comment]
итак. оставляем отчетность в том виде, в котором есть. только нужно добавить следующее:
1. столбец ИМ(интернет магазин, название)
2. финальную колонку с ПОСЛЕДНИМ статусом по заказу
3. итоговый отчет по двум статусам (ин процесс и комплитед). может быть третий сделать параметр, который будет соединять оба документа и исключать дубли. тем самым мы получим итоговую статистику по всем заказам за день. а на данный момент она у нас в двух файлах и заказы пересекаются

**Comment by andreyeduardovich** [comment]
4. и ОЧЕНЬ важно, чтобы статусы по заказам отображались только за тот период(фильтр по дате) за который выбрали.

**Comment by 8clever** [comment]
Paid
