### ISSUE TITLE
согласованная таблица отчетности по регионам

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#12]
необходимо создать отчетность, которую мы снимаем на странице статистика, по форме на странице ИЮНЬ РЕГИОНЫ - https://docs.google.com/spreadsheets/d/13Pg6F5foE3T0TXd6SR-LYKRaOQ5OFeM7dHTMr9Q6ANo/edit#gid=672931243

для примера, что снимаем  - страница 3 и 4 июня. итог, какой должен получаться - ИЮНЬ РЕГИОНЫ! 

3 и последующие круги должны суммироваться в третий. т.е. первый, второй круг. а третий + остальный круги суммарно все отражается в третьем круге.

**Comment by andreyeduardovich** [comment]
по кругам следующим образом выглядит таблица :

**Comment by 8clever** [comment]
5000
