### ISSUE TITLE
обзвон по второму кругу через новый транк манго 8 800

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#13]
сможешь мне сделать так, чтобы у нас второй круг шел через новый канал 8 800, который настроил Дима. я создал на всех беседу вк, он все завел вроде бы. всё ок. остается только тебе это реализовать в плане логики звонка. если мы звоним по заказу второй круг, то он должен идти через новый транк. если отдача будет хорошая, то сделаем каждый четный круг через 8 800. 

комментарий дима оставил такой :

все сделяль
транк mango1, многоканальный

**Comment by 8clever** [comment]
3000
