### ISSUE TITLE
модернизация статистики по регионам

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#15]
нужно чуть подредактировать статистику по регионам: 

вот ссылка на рабочую статистику. на проценты не обращай внимания. это мы сами их вставим. выделил цветом, какие строчки новые нужно добавить. 
https://docs.google.com/spreadsheets/d/13Pg6F5foE3T0TXd6SR-LYKRaOQ5OFeM7dHTMr9Q6ANo/edit#gid=540879453

сделал для примера строчки 1885-1893. желтым выделено то, что нужно добавить в статистику. объясняю: 

1. смотри в строчке 1885 - нужно считать заказы нот процессед(новые, которые поступили за день, где в номере нет 8800(маршрут, который мы отсееваем) получается, Что заказы по маршруту(8800) у нас сейчас тоже попадают в статистику, а там они не нужны. мы же звоним их вручную. поэтому и статистика неверная сейчас у нас. при этом строчку 1885 и 1886 не надо никуда плюсовать, как сейчас с нотпроцессед. просто цифры и всё. 

2. строчка 1892 говорит нам сколько было недозвонов по заказам из строчки 1885(поступивших за сегодня) и 1893 сколько у нас из всех заказов перенос сейчас есть. 

получается, то, что желтым делаем на всех регионах на всех кругах, а то, что синим - убираем. 

и вот тогда у нас статистика будет верная, наверное)))

**Comment by 8clever** [comment]
800

**Comment by andreyeduardovich** [comment]
всё ок, но надо параметр вывести на каждый круг по каждому региону. как мы с тобой тогда и обсудили.

under_call   (недозвон) по заказам за сег день
--

**Comment by andreyeduardovich** [comment]
не надо. я создам отдельную задачу.
