### ISSUE TITLE
Новая форма статистики от 14.07.19

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#21]
[TD_Статистика по дням_июль (1).xlsx](https://github.com/8clever/betacall/files/3389584/TD_._.1.xlsx)
у нас в принципе все собирается. просто им нужна вот в таком виде она теперь. нужно кое-что доработать, а что-то уже есть. давай сделаешь первую версию и я проверю? формулы все есть.

**Comment by andreyeduardovich** [comment]
если у нас для нот процессед сразу идет 2 круг обзвона(сразу на манго транк, как ты сказал), то нам нужно сделать так, чтобы нот процессед считался 0 кругом. нам нужна четкая статистика по обзвону. 1 круг с сотовых, 2 круг с манго, 3 и последующие с сотовых. иначе ничего анализировать не получается((( у нас новые заказы должны звониться в первый круг, а они получается попадют сразу во второй ,в манго.

**Comment by andreyeduardovich** [comment]
посмотри, пожалуйста комментарии.
[call_stats_by_day_2019_07_20_14_18.xlsx](https://github.com/8clever/betacall/files/3413530/call_stats_by_day_2019_07_20_14_18.xlsx)

**Comment by andreyeduardovich** [comment]
так. с этим все ок. вопросов нет. оплату тебе включи в счет за июль. оплата его должна быть на сл неделе.

они придумали новую форму. прилагаю ее. в принципе все у нас и так есть. они разбивку сделали еще по попыткам дозвона на тот или иной статус... ппц ребята работают. три формы сделай им, чтобы прийти к единой)))

итак. во вложении документ. 1 страница форма, которая у нас есть. 2 страница, форма, которую надо сделать теперь им.
[TD_Статистика_июль.xlsx](https://github.com/8clever/betacall/files/3464800/TD_._.xlsx)

**Comment by 8clever** [comment]
За новую статистику ну еще 5к сверху.

**Comment by andreyeduardovich** [comment]
12к за обе доработки ушли тебе на счет. нужна новая доработка. поясняю какая:

во вложении новая форма. начнут по порядку:
1. перенести итог, который был снизу наверх. т.е. теперь идет сначала итог, потом информация по старым заказам, потом по новым.
2. среднюю длительность обработки заказов перенести в ИТОГОВЫЕ показатели(наверх)
3. новая строка 17! тут нужно считать среднюю длительность до получения этих двух статусов дон и пик ап. ничего более.
4. сумма желтых строк не равна зеленой. потеряли где-то два заказа, отсюда и общая статистика отличается на 2 заказа.
5.. по каждому из показателей вынести процент в каждый статус. выделил эти строчки голубым цветом(новые строчки, которые нужно добавить в каждую статистику. в итоге процент у нас есть. только он почему-то на 100% не бьется.
6. там, где показатели с процентами - сделать значок процент в показателе процента. ЭТО ПИЗДЕЦ!!! надо же было такое включить в доработку. я в ахуе иногда с их хотелок. смотришь же процент, что тут непонятного?))) но надо, видимо.
7.и это уже вопрос - как у нас работает система и как считает заказа, которые к нам пришли, а потом топделивери перестало их отдавать:
а) при том, когда мы делали уже прозвон по заказу и он пропал у нас, т.к. мы болльше по нему не звоним
б) если заказ был новый и ни разу его не обработали и мск перестало его отдавать нам.

вот все 6 доработок и 7 пункт - это вопрос.

заранее спасибо!

**Comment by andreyeduardovich** [comment]
сегодня смотрел статистику, точно там маршрута нет с 8 800? по статусу без обработки - очень странные с утра показатели. может вечером, конечно, столько приходят
