### ISSUE TITLE
задачи от 24.08.19

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#22]
Вань, мне нужна помощь опять от тебя. очень нужна)))) как сделаешь - деньги сразу скину, как всегда. 
эти доработки нужны уже мне)) не пугайся, они адаекватные)))

1. надо убрать из статистики индикаторс - любые заказы из черного списка, а то там отображаются все, даже те, которые не звоним, такие как маршрут( префикс 8 800)
2. нужно добавить в черный список к 8 800 название одного интернет магазина. они нам передают эти данные в виде названия интернет магазина(Market Name):(дословно) Бета ПРО ООО Хом шоппинг раша и homshoppingrasha. надо только сделать так, чтобы мы точно не звонили по магазину Бета ПРО ООО Хом шоппинг раша и homshoppingrasha и по префиксу в номере 8 800. 
это были два приоритетных задания. 
далее опять же для меня просьба: 
3. можно ли сделать так, что если в системе есть такой параметр как NEW(в консоли, новый заказ), то параметр в конфиге addQueue сразу же бы падал до единицы, а когда параметр NEW - 0, возвращался бы в исходное положение. может быть и сразу онлайн редактирование этого параметра реализовать плюсом? 
4. можешь по логам глянуть, что у нас было с 7 до 9 утра 23.08.19. в 9 часов всё настолько заглючило, что не открывались даже страницы, пока не ребутнули сервер. 

первые две задачи очень важные, и у них приоритет. 

3 и 4 задачи - уже после 1 и 2 тогда. 

заранее тебе спасибо, как всегда :) скажешь потом сколько денег)))

**Comment by andreyeduardovich** [comment]
5 задача тоже срочная. нужно на главную страницу https://niti.betacall4all.ru/admin/ в выгрущку эксель по всем заказам добавить название магазина(маркет нэйм)

**Comment by 8clever** [comment]
3000 
все вместе за это и прошлые доработки
