### ISSUE TITLE
Задачи от 27.10.19

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#24]
1. у нас сейчас фильтр по звонкам стоит на 8800,8940, homshoppingrasha и нужно ДОБАВИТЬ интернет магазин hsr24.ru(дословно он так нам передается, как и предыдущее название, которое добавляли).
2. можно ли у девочек сделать в карточке клиента справа снизу где нибудь две галочки. обозвать параметр 1 и параметр 2. для чего это? иногда возникает ситуация, когда нужно собрать какую-то инфу по заказам, а хз как это сделать.... если только девочкам не копировать вручную номер заказа. а тут мы сможем собирать эту информацию по заказу(галочки) и в статистику может запихнешь в общий фильтр(кнопка excel), https://niti.betacall4all.ru/admin/stats
получается, там просто появятся еще две колонки параметр 1 и параметр 2. мне просто посчитать эти галочки, которые они будут статистику и сопоставить с заказами.
3. нужно в выгрузку общих заказов на главной странице, добавить параметр регион https://niti.betacall4all.ru/admin/ 

если не успеваешь сегодня, то в приоритете 1 задача и 3(

**Comment by 8clever** [comment]
сделал пункты 1 и 3
с тебя 1000 рублей.
