### ISSUE TITLE
задача от 10.11.2019

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#25]
необходимо добавить в игнор автообзвона НОВЫЙ параметр регион.
у нас сейчас блок идет по номеру телефона 8800, 8940
и два интернет магазина: hsr24.ru и homshoppingrasha

мне начнут передавать москву теперь в нашу систему и на неделю-две надо заблокировать ее от автообзвона. можно будет добавить блок на обзвон еще по параметру регион?
два параметра
Region: Москва
и
Region: Московская область

спасибо.

**Comment by 8clever** [comment]
добавил.
1000р.
