### ISSUE TITLE
задача от 08.12

### ISSUE THREAD

**Issue by andreyeduardovich** [8clever/betacall#26]
привет! как и спрашивал у тебя
1. надо сделать какое-то вплывающее окно или же надпись, чтобы девочки обращали внимание, что им попался на автообзвоне market mane hsr24.ru и homshoppingrasha
т.е. как ты и предлагал, или вплывающее окно сделать, что это ХШР или же вверху сигнализировать в открытом заказе в браузере. 

надо просто девочкам понимать, что пришел заказ по магазину ХШР и необходимо использовать дургой скрипт.

2. удалить блок  на обзвон с market name hsr24.ru и homshoppingrasha для того, чтобы они уходили в автоматический обзвон. остальной фильтр оставить без изменений.

3. + должен тебе за работу на этой недели с димой.

**Comment by 8clever** [comment]
2000р за все
